version: '2.1'

services: 
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  service-registry:
    image: service-registry:latest
    ports:
      - 8761:8761
  config-server:
    image: config-server:latest
    ports:
      - 8888:8888
  auth-server:
    image: aindriub/auth-server:latest
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=${MYSQL_HOST}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_PORT=${MYSQL_PORT}
  api-gateway:
    image: aindriub/api-gateway:latest
    ports:
      - 8080:8081